apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wk5mf1n91-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wk5mf1n91-go 
  name: wk5mf1n91-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wk5mf1n91-go 
